# numpy

# Numpy numercial python 개요
	- 파이썬에서 선형대수 기반의 프로그램을 쉽게 만드는 라이브러리
	- 반복문 없이 대량의 데이터의 배열 연산가능 > 심지어 빠른 배열 연산 속도 보장.
- 대량의 데이터 기반의 과학 및 공학에서 빠른 계산 가능, C/C++ 같은 저수준의 언어 - 기반의 호환 API 제공

In [14]:
import numpy as np



# 1차원 배열 만들기 | 타입,차원,shape확인array1 = np.array([7, 2, 9, 10])
print(array1)  # [ 7  2  9 10]
print(type(array1))
print(array1.ndim)  # 1 1차원이다.
print(array1.shape)  # (4,)  4개의 원소

array2 = np.array([[5, 23, 45], [2.1, 2, 3]])
print(array2)
print(array2.ndim)  # 2차원이다.
print(array2.shape)  # (2,3) 2개의 원소 , 각각에는 3개의 원소

array3 = np.array([
    [[1, 2, 3], [4, 5, .16], [7, 8, 9]], [[11, 12, 13], [14, 15, 16], [17, 18, 19]]])
print(array3)
print(array3.ndim)  # 3  3차원이다.
print(array3.shape)  # (2, 3, 3) 2 개의 원소 , 각각에는 3개의 원소, 그 속에는 3개의 원소
print(array3.dtype)  # float64

[ 7  2  9 10]
<class 'numpy.ndarray'>
1
(4,)
[[ 5.  23.  45. ]
 [ 2.1  2.   3. ]]
2
(2, 3)
[[[ 1.    2.    3.  ]
  [ 4.    5.    0.16]
  [ 7.    8.    9.  ]]

 [[11.   12.   13.  ]
  [14.   15.   16.  ]
  [17.   18.   19.  ]]]
3
(2, 3, 3)
float64


# 타입

- ndarray 내의 데이터값은 숫자,문자,불값 다 가능
- int (8,16,32)bit, unsigned int (8,16,32)bit, float (16,32,64)bit
- ndarray


In [5]:

# ndarray - 타입 지정

arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int)
print(arr1, arr1.dtype)
print(arr2, arr2.dtype)


[1. 2. 3.] float64
[1 2 3] int32


In [6]:

# 타입 변환 -> 메모리절약을 위해 주로 사용 astype


array_int = np.array([1, 2, 3, ])
array_float = array1.astype('float64')
print(array_int.dtype, array_float.dtype)  # int32 float64

int32 float64


In [8]:

# axis 기반 연산 -sum

arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3.sum())
print(arr3.sum(axis=0))  # [5 7 9]
print(arr3.sum(axis=1))  # [ 6 15]

21
[5 7 9]
[ 6 15]


In [9]:

# ndarray 편리한 생성 : arrange, zeros, ones

# arrange(): 연속값을 요소로 가지는 ndarray 생성
# zeros(): 0으로 초기화된 ndarray 생성
# ones(): 1으로 초기화된 ndarray 생성

arr4 = np.arange(10)  # 0부터 9까지 들어감
print(arr4)  # [0 1 2 3 4 5 6 7 8 9]
arr5 = np.zeros((4, 3), dtype='int32')
print(arr5)  # 4개원소 각각 3개의 원소가, 있어, 다 0이야.
arr6 = np.ones((4, 3), dtype='int32')
print(arr6)  # 4개원소 각각 3개의 원소가, 있어, 다 1이야.

[0 1 2 3 4 5 6 7 8 9]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [10]:

# ndarray - 차원 크기 변경 : reshape()


arr7 = np.arange(10)
print(arr7)
arr7 = arr7.reshape(2, 5)
"""
[[0 1 2 3 4]
 [5 6 7 8 9]]
"""
print(arr7)
arr7 = arr7.reshape(5, 2)
print(arr7)
"""
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
"""

arr7 = arr7.reshape(-1, 5)  # 몇개의 덩어든, 5개씩 묶어.
print(arr7)
"""
[[0 1 2 3 4]
 [5 6 7 8 9]]
"""
arr7 = arr7.reshape(5, -1)  # 5개의 덩어리도 만들어, 몇개씩 들어있는지는 몰라.
print(arr7)
"""
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
"""
arr7 = arr7.reshape(-1, 1) 
print(arr7)
"""
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
"""
arr7 = arr7.reshape(-1, )  # flatten
print(arr7)  # [0 1 2 3 4 5 6 7 8 9]


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 2 3 4 5 6 7 8 9]
