

# ndarray - 인덱싱 ( indexing )

특정 위치 단일값, 슬라이싱 , 펜시 인덱싱, 불린 인덱싱





In [4]:


# 특정 위치 읽기, 쓰기

import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[0], arr[1], arr[2])  # 1 2 3
print(arr[-1], arr[-2])  # 4 3
arr[0] = 99
print(arr)  # [99  2  3  4]

barr = np.arange(start=1, stop=10)
arr = barr.reshape(3, 3)  # reshape, 1 depth 추가
print(arr)
print(arr[0, 0], arr[0, 1], arr[0, 2], arr[1, 0], arr[1, 2])  # 1 2 3 4 6


1 2 3
4 3
[99  2  3  4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 2 3 4 6


In [7]:


# array - 슬라이싱  읽기, 쓰기

import numpy as np

# 1차원 슬라이싱
arr = np.array([1, 2, 3, 4])
print(arr[2:])  # [3 4]


# 2차원 슬라이싱
arr = np.array(
    [
        [1, 2, 3, 4, ],
        [6, 7, 8, 9, ],
        [11, 12, 13, 14]
    ]
)

print(arr)
# 우선 1축 2번째 까지만 컷팅, 2축 도
print(arr[:2, :2])
# 1축 2부터 컷팅, 2축도
print(arr[2:, 2:])
#
print(arr[1:, :])


[3 4]
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]
[[1 2]
 [6 7]]
[[13 14]]
[[ 6  7  8  9]
 [11 12 13 14]]


# arr[ TYPE = 정수,불리언,:,[] ]
- 정수 : 단일값
- : 슬라이싱
- [] 특정 인덱스 추출 펜시인덱싱
- 블리언 : 조건값


In [6]:
# 팬디 인덱싱

# 내가 원하는 인덱스를 선택해서 묶는다.

import numpy as np


arr = np.array([1, 2, 3, 4])
print(arr)
print(arr[[1, 3]])  # 1번과, 3번 인덱스만들 골라서 가져옴

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr)

print(arr[[0, 2]])

print(arr[[0, 2], 1])
"""
[2 8]
"""
print(arr[[0, 2], :])
"""
[[1 2 3]
 [7 8 9]]
"""
print(arr[[0, 2], 1:2])
"""
[[2]
 [8]]
"""


[1 2 3 4]
[2 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]
[2 8]
[[1 2 3]
 [7 8 9]]
[[2]
 [8]]


In [9]:
# 블리언 인덱싱

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr > 3)  # [False False False  True  True]

print(arr[[False, False, False,  True, True]])  # [4 5]


print(arr[arr > 3])  # [4 5]

# arr[ TYPE = 정수,불리언,:,[] ]
# 정수 : 단일값
# : 슬라이싱
# [] 특정 인덱스 추출 펜시인덱싱
# 블리언 : 조건값


print(arr[[3, 4]])  # [4 5]


[False False False  True  True]
[4 5]
[4 5]
[4 5]


# 넘파이 sort()유형

- np.sort() 원본 유지, 정렬된 배열 반환
- ndarray.sort()  원본 자체를 정렬한다

In [ ]:

import time
import numpy as np

f"""
넘파이 sort()유형

- np.sort() 원본 유지, 정렬된 배열 반환
- ndarray.sort()  원본 자체를 정렬한다
"""
arr = np.array([4, 2, 1, 9])
print(arr)  # [4 2 1 9]

arr_sorted = np.sort(arr)
print(arr_sorted)  # [1 2 4 9]
print(arr)  # [4 2 1 9]


arr.sort()
print(arr)  # [1 2 4 9]



# 내림차순으로 정렬하기

In [ ]:
# 내림차순으로 정렬하기

arr2 = np.array([6, 1, 4, 2, 699, 3])
arr2_rev = np.sort(arr2)[::-1]
print(arr2_rev)  # [699   6   4   3   2   1]



# axis 기반의 sort()

In [ ]:
# axis 기반의 sort()
arr3 = np.array([
    [8, 12],
    [7, 1]
])
print(np.sort(arr3, axis=0))  # 축 1차, 로 정렬  |
print(np.sort(arr3, axis=1))  # 축 2차, 로 정렬  ㅡ



# argsort() : 원본 행렬 정렬시, 원래 행렬의 인덱스가 필요할때


In [ ]:
# argsort() : 원본 행렬 정렬시, 원래 행렬의 인덱스가 필요할때

org_arr = np.array([3, 1, 9, 5])
print(np.sort(org_arr))  # [1 3 5 9]

sort_indices = np.argsort(org_arr)
print("행렬 정렬시 원본 행렬의 인덱스", sort_indices)  # [1 0 3 2]
print(org_arr)  # [1 3 5 9]
print(org_arr[[1, 0, 3, 2]])  # [1 3 5 9]
print(org_arr[sort_indices])  # [1 3 5 9]


# key -value 형태의 데이터를 가지고 정렬하기

In [ ]:
# key -value 형태의 데이터를 가지고 정렬하기


name_arr = np.array(['jojn', 'mkei', 'srahc', 'kata', 'sameul'])
score_arr = np.array([78, 15, 64, 88, 48])

sort_indices = np.argsort(score_arr)
print("sort_idx", sort_indices)
name_rank_arr = name_arr[sort_indices]
print(name_rank_arr)  # ['mkei' 'sameul'  'srahc' 'jojn' 'kata']
print(name_rank_arr[::-1])  # ['kata' 'jojn' 'srahc' 'sameul' 'mkei']


# Numpy 응용

In [ ]:
# Numpy 응용
"""
- 행렬 내적 : np.dot(A,B)
- 전치 행렬 : np.transpose(A)
-
"""

A = np.array([[1, 2, 3, ], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
print(np.dot(A, B))
"""
[[ 58  64]
 [139 154]]
"""
transpose = np.transpose(A)
print(transpose)
"""
[[1 4]
 [2 5]
 [3 6]]
"""



# 백터화 연산 : for문 미사용

In [ ]:
# 백터화 연산 : for문 미사용

cvalues = [25.3, 42.8, 26.9]
C = np.array(cvalues)
print(C)
F = C*9/5+32
# <class 'numpy.ndarray'> [ 77.54 109.04  80.42]
print(type(F), F)

F1 = [x*9/5+32 for x in cvalues]
# <class 'numpy.ndarray'> [77.54, 109.03999999999999, 80.42]
print(type(F), F1)


# list와 ndarray 계산 성능
- 100배 차이?!
- np.array에서 for문을 돌리면 오히려 느리다.

In [10]:
import time

size_of_vec = 10000000
X = list(range(size_of_vec))
Y = list(range(size_of_vec))
Z = list(range(size_of_vec))

start = time.time()
for i in range(len(X)):
    Z[i] = X[i] + Y[i]
print("time : ", time.time()-start)


time :  2.671229600906372


In [11]:
import numpy as numpy
import time

size_of_vec = 10000000
X = np.arange(size_of_vec)
Y = np.arange(size_of_vec)

start = time.time()
Z = X + Y
print("time : ", time.time()-start)

time :  0.02100348472595215


In [12]:
import numpy as numpy
import time

size_of_vec = 10000000
X = np.arange(size_of_vec)
Y = np.arange(size_of_vec)
Z = np.zeros(size_of_vec)

start = time.time()
for i in range(len(X)):
    Z[i] = X[i]+Y[i]
print("time : ", time.time()-start)

time :  6.430346250534058
